version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    env_file:
      - backend/.env  # Load environment variables
    environment:
      POSTGRES_USER: "nutrition_user"
      POSTGRES_PASSWORD: "nutrition_pass"
      POSTGRES_DB: "nutrition_db"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    depends_on:
      - db
    env_file:
      - backend/.env
    environment:
      DATABASE_URL: postgresql://nutrition_user:nutrition_pass@db:5432/nutrition_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    depends_on:
      - backend
    ports:
      - "8080:8080"
    # Volume mount removed to prevent overriding copied files

volumes:
  pg_data:
